### ISSUE TITLE
What if all route parameters are optional?

### ISSUE THREAD

**Issue by suntong** [gofiber/docs#114]
Is https://github.com/gofiber/docs/blob/master/original/routing.md#parameters the only way to handle query parameters? Unlike

`GET /user/:name/books/:title`

I need all route parameters to be optional. E.g.,

`https://mysite.com/?page=2&limit=3&sort=price`

What if I just need to specify the last one? (no matter how you arrange the route parameters orders, there will always be a last one)

How to deal with situation like this?  
Please help. Thanks a lot!

**Comment by Fenny** [comment]
Hi @suntong, do you mean <https://docs.gofiber.io/ctx#query>?

**Comment by suntong** [comment]
Perfect! Thanks for the swift reply @Fenny!
