### ISSUE TITLE
Session error with redis session

### ISSUE THREAD

**Issue by vietlib** [gofiber/docs#158]
I use redis as session middleware service. But get error when reload page or open a new page if my script get session info

Here is the error alert: ```[session] Register this type first with the `RegisterType` method.```

This error also happen when restart server

I have to restart server, clear history, restart redis to continue working

**Comment by akshaybabloo** [comment]
You might want to create a new issue at https://github.com/gofiber/fiber

**Comment by ReneWerner87** [comment]
We know about this bug and we still have a bug for that.
