### ISSUE TITLE
website documentation gives broken link as reference

### ISSUE THREAD

**Issue by UlasSAYGINIM** [gofiber/docs#163]
hi,

2 links are not working on https://docs.gofiber.io/api 

one is used on https://docs.gofiber.io/api/ctx#links

in content "the response’s Link HTTP header field."

https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Link

second link below is not working and it is used on https://docs.gofiber.io/api/ctx#next

https://github.com/gofiber/docs/tree/aa2680660c0b661b8e9d215b32cb03e766277131/api/error-handling.md

**Comment by ReneWerner87** [comment]
thx

fixed with https://github.com/gofiber/docs/commit/9dd3d43868e235182c7749397a8ce1f1f62874e0
