### ISSUE TITLE
group by params

### ISSUE THREAD

**Issue by alfuhigi** [gofiber/docs#178]
Hi evereyone  can we have example in `grouping.md` that show we can group router by params
something like this or example more simple 
```go

func main() {
  app := fiber.New()

  api := app.Group("/api")      // /api

  v1 := api.Group("/v1")        // /api/v1
  user := api.Group("/user")
  userID := user .Group("/:userID")
  v1.Get("/list", handler)      // /api/v1/list
  user.Get("/", handler)      // /api/v1/user
  userID.Get("/profile",handler) // /api/v1/user/1/profile
  userID.Put("/update",handler) // /api/v1/user/1/update

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/guide/grouping#paths

Should be enough, otherwise you can also create a pull request, as long as the example fits well into the documentation, that would be okay.

**Comment by alfuhigi** [comment]
ya... you right ,maybe I will in recipes! . Docs should be simple and clear ... thx :)
