### ISSUE TITLE
Wrong example header

### ISSUE THREAD

**Issue by ansidev** [gofiber/docs#213]
https://github.com/gofiber/docs/blob/master/api/middleware/logger.md#L37

Ref commit: https://github.com/gofiber/docs/commit/f642a76347b84eb0841edf5e0dc0aa7acc57a522#diff-53668909cb86fa542f3cf7e888e9a5dbda2def6b92e2101268a56e0a81966136R39-R45

**Comment by ReneWerner87** [comment]
thx for the hint
