### ISSUE TITLE
It's not possible to copy-paste portions of example code

### ISSUE THREAD

**Issue by fishnux** [gofiber/docs#248]
Hi,

It's not possible to copy-paste portions of the example code. Am I the only one experiencing this problem?

I'm using Firefox. Thanks!

**Comment by ReneWerner87** [comment]
i tested it 
![image](https://user-images.githubusercontent.com/7063188/157205534-58cacc39-e7ef-4a65-b68f-7e595b22a29b.png)
its working in my browser

at the end this is something for gitbook 
![image](https://user-images.githubusercontent.com/7063188/157205629-b197360e-32d5-49fa-86a2-766e78863e4c.png)
