### ISSUE TITLE
Incorrect usage of `Location`

### ISSUE THREAD

**Issue by alexgokhale** [gofiber/docs#259]
The example provided for `ctx.Location` [here](https://github.com/gofiber/docs/blob/master/api/ctx.md#Location) indicates that `Location` doesn't have a return value in its signature, however in the code below `c.Location("/test")` is returned. This code fails to compile.

**Comment by leonklingele** [comment]
Is this still valid?

**Comment by ReneWerner87** [comment]
fixed with https://github.com/gofiber/docs/commit/7c3421dc5c2a3db045661017da1e8a8b8fb4e793
