### ISSUE TITLE
🤔 Docusaurus Migration for Fiber Docs

### ISSUE THREAD

**Issue by efectn** [gofiber/docs#284]
Docusaurus 2 is fast, flexible and free documentation generator. I think it would be better if we use Docusaurus instead of Gitbook. Gitbook isn't open source and a bit slow in mobile devices. Check out https://docusaurus.io/. I think we can use it by closing homepage, blog features. 

What do you think?

**Comment by ReneWerner87** [comment]
sure
why not, I am currently not clear about the benefits, but I hope everything we need we can realize with it

**Comment by efectn** [comment]
> sure why not, I am currently not clear about the benefits, but I hope everything we need we can realize with it

I think it's important thing to be open-source.
Also it supports localization. Maybe someone would like to add other languages for docs https://github.com/gofiber/docs/issues/222

**Comment by ReneWerner87** [comment]
We had tried internationalization before and found it difficult because a lot of maintenance is needed, which is not really necessary since every developer should be able to read English documentation.

**Comment by efectn** [comment]
> You mean that we use more open source tools? Because with the kind of generation it doesn't really change that we are more open source.

Yes but it's not the main reason. Docusaurus is really extendable when to compare it with Gitbook
