### ISSUE TITLE
Typo in Fiber API documentation

### ISSUE THREAD

**Issue by JobaerAhamed** [gofiber/docs#317]
The [Fiber API Documentation](https://docs.gofiber.io/api/fiber) has a typo on the `TrustedProxies` section:
```
Contains the list op trusted proxy IP's. Look at EnableTrustedProxyCheck doc.
```
I think it should be "Contains the list `of` trusted proxy IP's"

**Comment by ReneWerner87** [comment]
thx 
fixed with https://github.com/gofiber/docs/commit/685c21bdfe4d9fc8021e78dc95123d10e528e087
