### ISSUE TITLE
Hook icon doesn't render in Chrome

### ISSUE THREAD

**Issue by Serpentarius13** [gofiber/docs#364]
![image](https://github.com/gofiber/docs/assets/112726943/2f65d918-545c-4481-bc2e-5884fc901deb)

But works in Firefox
![image](https://github.com/gofiber/docs/assets/112726943/0a9e79b6-26a1-4670-be71-91f74f39d141)

Proposition: change icon to something rendering in both Chrome and Firefox:
🎣
![image](https://github.com/gofiber/docs/assets/112726943/eb72ba2f-9d0a-4b43-8d19-527fd30cd75d)

>:)

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/commit/ada2d4affdde6f3a998cc53e92a0c262dff07708

**Comment by Serpentarius13** [comment]
Needs rebuild I guess

**Comment by ReneWerner87** [comment]
Check the "Next" version, the change for v2 is coming with the next release
