### ISSUE TITLE
Trailing `}` in regex constraint

### ISSUE THREAD

**Issue by giraffesyo** [gofiber/docs#368]
Hello, 

I see theres a trailing `}` in the regex constraints on this docs page: https://docs.gofiber.io/next/guide/routing#constraints

I'm not sure if that is intended or not, but it seems to work without that. If it's not intended, I can open a PR to remove that. 

![image](https://github.com/gofiber/docs/assets/10459772/f65dc46e-591c-4c39-bac5-37f8edac5386)

**Comment by ReneWerner87** [comment]
Yes its to much
Can you correct it

**Comment by ReneWerner87** [comment]
Readme source is in the core repository

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/commit/4099ef87bb35db39c160c17b9b6ded34e71d007d
