### ISSUE TITLE
bug: using search bar appends doc path twice 

### ISSUE THREAD

**Issue by huizhuansam** [gofiber/docs#414]
**Expected behavior:**
Clicking on the search bar's suggested items will navigate user to correct page.

**Current behavior:**
Every search result will direct user to 404 not found page.
 
**Reproduce the bug:**
Type into the search bar and click on any one of the suggested results.

For example, the URL becomes [https://docs.gofiber.io/api/client/api/client#multipartform] instead of [https://docs.gofiber.io/api/client#multipartform]. Note the repeated `api/client` part of the URL.

This might be related to a bug in the `@easyops-cn/docusaurus-search-local` dependency. See https://github.com/easyops-cn/docusaurus-search-local/issues/422 for relevant issue. Seems like a version bump solves this problem - tested it locally and it works.

**Comment by gaby** [comment]
@huizhuansam Thanks for the report, we were discussing this on Discord at the moment. Will report back.

**Comment by gaby** [comment]
Yeah we are using an old version -> `"@easyops-cn/docusaurus-search-local": "^0.40.1"`

**Comment by huizhuansam** [comment]
Should I make a PR to fix this? Seems trivial, I don't mind helping out

**Comment by gaby** [comment]
@huizhuansam Sure, go ahead.

**Comment by huizhuansam** [comment]
@gaby I'm trying to push a fix branch to the repo, can you give me access? Thanks :)
