### ISSUE TITLE
We need create doc to guide constants on Fiber

### ISSUE THREAD

**Issue by renanbastos93** [gofiber/docs#87]
Any suggestion?

I thought something like that
```
explain possibles constants to use on Fiber
fiber.<constant>

e.g
fiber.StatusInternalServerError // get status errors 500 respect RFC XYZ all list to use Status Code can you based on IANA


list constants: we can show as a table
show list below
```

**Comment by Fenny** [comment]
We use the same constants as the `net/http` package, they can be found here:
https://github.com/gofiber/fiber/blob/master/utils.go#L531

I will accept PR's explaining/showing these variables 👍
