### ISSUE TITLE
Missing some opening parentheses

### ISSUE THREAD

**Issue by Rantignac** [gofiber/docs#94]
Missing some opening parentheses at the import level in the Middleware examples for part the compression and webSocket 
![image](https://user-images.githubusercontent.com/35865413/82460519-8dfcbe80-9ab9-11ea-8143-7f7aae568ff5.png)

**Comment by thomasvvugt** [comment]
Hi @Rantignac 
Could you refer to the specific occurrences in our documentation?
You can also create a PR yourself if you fancy.
Thanks for opening this issue! 😊
