### ISSUE TITLE
Portuguese flag on README

### ISSUE THREAD

**Issue by fsmiamoto** [gofiber/docs#98]
The Portuguese translation seems to be in Brazilian Portuguese so it would make more sense to change the flag to a Brazilian one.

With this change, the flag would also match with the one shown in the translation platform.

If you guys agree, I'd be willing to make a PR for it.

**Comment by Fenny** [comment]
We removed the translations for now because It's not compatible with the new version. We will take your suggestion into account when we re-open the translations again 👍
